### ISSUE TITLE
Simple Test fails (gulp)

### ISSUE THREAD

**Issue by CREEATION** [juice49/ExpandOBem#1]
Hello,

I have my test.jade with:

``` jade
h1 Test!
```

when running it like this:

``` javascript
gulp.task('jade', function () {
  return gulp.src('test.jade')
    .pipe(jade({ pretty: true }))
    .pipe(transform(expandobem.processStream))
    .pipe(gulp.dest('html'));
});
```

the resulting HTML looks like... this:

``` html
<h11>Test!</h1>
```

With proper doctype, head, body, etc. it works as it should, by the way.

**Comment by juice49** [comment]
Hi @CREEATION, I have just tried compiling both HTML and Jade with success.

The issue only occurs only when `pretty: true` is set for Jade compilation, however removing the ExpandOBem step does fix the issue.

I will have a look into this, thanks for reporting!

**Comment by juice49** [comment]
Fixed in 0.0.4

**Comment by CREEATION** [comment]
Thanks! But I have a problem using it in my gulpfile.
It starts the task, but it just... doesn't end properly.

`[17:48:51] Starting 'templates'...`
`my_project >`

It never says finished, like `[17:47:12] Finished 'templates' after 8.38 s`.

**Comment by juice49** [comment]
I've just experiences this myself! I'm very sorry for pushing a broken release, and will try and fix this evening. Thanks for reporting!

**Comment by CREEATION** [comment]
No problem, it's okay because your package is awesome!

**Comment by juice49** [comment]
I don't seem to be able to recreate the issue now. I'll try again on the machine I had problems with tomorrow.

I've also tried adding `gulp-watch`, but everything still works just fine. For reference, this is the configuration I am using:

## node

io.js 1.4.3

## package.json

```
{
  "name": "expandobem-test",
  "version": "1.0.0",
  "dependencies": {
    "expandobem": "0.0.4",
    "gulp": "^3.8.11",
    "gulp-jade": "^1.0.0",
    "gulp-watch": "^4.1.1",
    "vinyl-transform": "^1.0.0"
  }
}
```

[(actual versions installed)](https://gist.github.com/juice49/54a182d5dfb68f340b8e)

## gulpfile.js

```
const gulp = require('gulp');
const transform = require('vinyl-transform');
const jade = require('gulp-jade');
const expandobem = require('expandobem');

gulp.task('default', function() {
    return gulp.src(['./*.jade'])
        .pipe(jade())
        .pipe(transform(expandobem.processStream))
        .pipe(gulp.dest('./dist'));
});
```

## index.jade

```
.widget--big
    .widget__header--featured--poi
        h1 baz
```

@CREEATION the Jade todo is to see if this can be used with Jade outside of a build process, i.e. when serving Jade with Express.

**Comment by CREEATION** [comment]
Strange... sadly I have to use `{ pretty: true }`.
Here's my current setup:

# node

`v0.10.33`

# package.json

``` json
{
  "private": true,
  "devDependencies": {
    "css-sprite": "^0.9.0",
    "expandobem": "0.0.4",
    "glob": "^4.1.1",
    "gulp": "^3.8.8",
    "gulp-autoprefixer": "^1.0.1",
    "gulp-beautify": "^1.1.1",
    "gulp-combine-media-queries": "^0.2.0",
    "gulp-concat": "^2.4.1",
    "gulp-convert-encoding": "0.0.2",
    "gulp-css-globbing": "^0.1.5",
    "gulp-cssimport": "^1.3.1",
    "gulp-csso": "^0.2.9",
    "gulp-flatten": "0.0.4",
    "gulp-if": "^1.2.5",
    "gulp-imagemin": "^1.2.1",
    "gulp-insert": "^0.4.0",
    "gulp-jade": "^0.11.0",
    "gulp-plumber": "^0.6.6",
    "gulp-rename": "^1.2.0",
    "gulp-ruby-sass": "^0.7.1",
    "gulp-stripbom": "^1.0.1",
    "gulp-uglify": "^1.0.1",
    "imagemin-pngcrush": "^4.0.0",
    "path": "^0.11.14",
    "sass-convert": "^0.5.0",
    "sassdoc": "^2.1.1",
    "streamqueue": "^0.1.3",
    "vinyl-transform": "0.0.1"
  }
}
```

# gulpfile.js

### stripped down version

``` javascript
var gulp = require('gulp');
var jade            = require('gulp-jade');
var jadeGlobbing    = require('gulp-jade-globbing');
var plumber         = require('gulp-plumber');
var transform       = require('vinyl-transform');
var expandobem      = require('expandobem');
var rename          = require('gulp-rename');
var encode          = require('gulp-convert-encoding');
var stripBom        = require('gulp-stripbom');
var path            = require('path');

gulp.task('templates', function () {
  return gulp.src([
      paths.src.views + '/**/*.jade',
      '!' + paths.src.views + '/**/{_*,_*/**}'
    ])
    .pipe(plumber())
    .pipe(jadeGlobbing({
      placeholder: {
        'default-layout': paths.src.root + '/layout/templates/default.jade',
        'utilities': paths.src.root + '/utilities/jade/**/*.jade',
        'modules': paths.src.root + '/modules/**/*.jade',
        'layouts': paths.src.root + '/layout/**/*.jade',
      },
      ignore: [
        paths.src.root + '/layout/templates',
        paths.src.root + '/views',
        paths.root + '/views',
      ]
    }))
    .pipe(jade({ pretty: true }))
    .on('error', console.error.bind(console))
    .pipe(transform(expandobem.processStream))
    .pipe(rename(function (path) {
      path.extname = '.blade.php';
    }))
    // Encode to UTF-8 and strip BOM
    .pipe(encode({ to: 'utf8' })).pipe(stripBom())
    .pipe(gulp.dest(paths.dest.views));
});
```

**Comment by CREEATION** [comment]
I tried using different methods to use expandobem, e.g. processFile, processString,...
nothing works. It always returns some object I can't identify :(

**Comment by CREEATION** [comment]
Okay, so... without a doctype or comments it works.

### compiles

``` jade
//- doctype html
h1.expecto--patronum Hello World
```

### nope

``` jade
doctype html
h1.expecto--patronum Hello World
```

## with normal comments

### jade

``` jade
// Hello World
h1.expecto--patronum Hello World

```

### html output

``` html
<undefined> Hello World--><h1 class="expecto expecto--patronum">Hello World</h1>
```

Seems like it parses all `--`'s?

//e: got it fixed locally, pull request incoming!

**Comment by juice49** [comment]
Thanks for helping out with this! I am not sure why limiting the selector to elements with a `class` attribute makes a difference—ExpandOBem only operates on the class attribute—but I have just published this as `0.0.5` as it's working for you. It should be on npm shortly (:

I'll continue to look into making ExpandOBem more robust, especially with Jade, as there may be something deeper going on here to work out. I also plan on adding a CLI tool.

Thanks again and have a great weekend!

**Comment by CREEATION** [comment]
Could be a problem with trumpet, maybe?

**Comment by CREEATION** [comment]
Hello,

the problem occurs again, updated all my dependencies:

```
root ) gulp html
[15:31:00] Using gulpfile /.../gulpfile.js
[15:31:00] Starting 'clean-html'...
[15:31:00] Finished 'clean-html' after 2.9 ms
[15:31:00] Starting 'html'...
root )
```

Seems like my "fix" wasn't really a fix :C

**Comment by CREEATION** [comment]
I just realised everything works fine again, so... closing this :)
