### ISSUE TITLE
processStream error without giving options

### ISSUE THREAD

**Issue by CREEATION** [juice49/ExpandOBem#6]
Hello again,

I get the following error when trying to just use expandobem.processStream without any options:

```
/.../node_modules/expandobem/index.js:168
        includes(singleClass, options.syntax.element) ||
                                            ^
TypeError: Cannot read property 'element' of undefined
```

However, when passing the default options through, everything works fine, e.g.:

``` javascript
    .pipe(transform(expandobem.processStream({
      syntax: {
        element: '__',
        modifier: '--'
      }
    })))
```

**Comment by juice49** [comment]
Hi Thomas, thanks again for the bug report. I have tracked this down to the [merge-deep](https://www.npmjs.com/package/merge-deep) module; specifically version 1.0.2 that was released two weeks ago. This version seems to result in an empty object when I merge the user options with the default options. I have for now simply fixed the merge-deep dependency to version 1.0.1 which works as expected.

I've just published this patch to npm as version 0.1.1. Obviously this isn't a great fix, and I'd like to look into the merge-deep (or switch out that module) when I get a chance. But for now it fixes the problem :smile:

Thanks!

**Comment by CREEATION** [comment]
I think it's good to remove dependencies (for cases like this), so why not write your own merge method? =)

**Comment by juice49** [comment]
There has actually been a new version of merge-deep released that looks like it fixes this bug. If I'd had a little more time (I should have made more time) to make a test case, I would have submitted an issue to the merge-deep repo and/or submitted a patch.

This, I believe, is a better approach than writing my own merge function that will be prone to its own errors... but will have nobody to identify or patch them. I'd much rather be part of a community sharing a tool and making it better together :D

Modularity (and having tiny tools that do one thing) is a part of the node and unix mindset that I really love.
